
try {
    console.log(numero)
} catch (error) {
    console.log(`Ocorreu o erro ${error}`)
    console.log(error)
} finally {
    console.log('Finalizando programa...')
}